# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

jobs:
  build:
    docker:
      - image: iamjdg11/docker-react-app
    steps:
      - checkout
      - run: sudo docker run -e CI=true iamjdg11/docker-react-app npm run test -- --coverage

